# Site
repository: sproogen/resume-theme
favicon: https://i.ibb.co/syrsmb1/026.png

# Content configuration version
version: 2

# Personal info
name: 范植貿
title: Chi-Mao Fan
email: qaz5517359@gmail.com
# website: www.github.com/sproogen/resume-theme

# Dark Mode (true/false/never)
darkmode: true

# Social links
# twitter_username: Fan_R_Mao
github_username:  FanChiMao
# stackoverflow_username: "17114617"
facebook_username: 52hzfan
instagram_username: 52hz_fan
linkedin_username: 植貿-范-432665220
# youtube_username: channel:fooUCIV7WMa5O_TZKZZSzXcLmmw


# Additional icon links
#additional_links:
# - title: itsgoingto.be
#  icon: fas fa-globe
#  url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
about_title: Personal Profile
about_profile_image: https://i.imgur.com/m2rDOMa.jpg
about_content: | # this will include new lines to allow paragraphs
  **Hello World! 我是范植貿，今年25歲，來自新竹，現居台中。**
  
  2022畢業於中興大學研究所，


content:
  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: 國立中興大學 (NCHU)
        caption: Sep 2020 - present
        sub_title: 電機工程研究所
        description: | # this will include new lines to allow paragraphs
          
      - layout: left
        title: 元智大學 (YZU)
        caption: Sep 2015 - Aug 2020
        sub_title: 電機工程學系
        description: | # this will include new lines to allow paragraphs
                            
  - title: Research Experiences # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: 碩士論文
        caption: Sep 2021 - Mar 2022
        link: https://drive.google.com/file/d/1PKB0Mb02cmNcB5zCae_SYDbgPr4w86xy/view?usp=sharing
        link_text: Thesis pdf
        quote: >
          利用可選擇性殘差塊在改良式階層編解碼器網路實現影像修復
          <br />Image Restoration by Selective Residual Block on Improved Hierarchical Encoder-Decoder Networks  
        additional_links:
          - title:  Thesis
            icon: fab fa-github
            url: https://github.com/FanChiMao/SRMNet-thesis
        description: | # this will include new lines to allow paragraphs
          ① 我們提出了改良版的階層式編解碼器架構: MINet+。  
          ② 我們提出了一種平衡型模塊，稱為選擇殘差模塊(Selective Residual Block)。  
          ③ 我們提出了一個全新的特徵融合方式，稱為選擇小波特徵融合(Selective Wavelet Feature Fusion)。  
          ④ 我們提出一個高性能的影像修復模型，能處理5種不同的影像修復任務，並測試於超過10個資料集。  
                  
      - layout: left
        title: IMBD 競賽
        caption: Sep 2021 - Dec 2021  
        link: https://imbd2021.thu.edu.tw/
        link_text: Competition website
        quote: >
          2021全國智慧製造大數據分析競賽
          <br />National Intelligent Manufacturing Big Data Analysis Competition  
        additional_links:
          - title:  Competition-2021-Pytorch-Reggression
            icon: fab fa-github
            url: https://github.com/FanChiMao/Competition-2021-Pytorch-Reggression
          - title: award
            icon: fas fa-award
            url: https://i.imgur.com/SIQyjTo.jpg
        description: | # this will include new lines to allow paragraphs  
          ① 利用現成業界模具機台的參數數據，用深度學習方式預測晶圓或產品品質。  
          ② 在118個隊伍中，得到前31名並通過初賽。  

      - layout: left
        title: 期末專題
        caption: May 2021 - July 2021
        link: https://drive.google.com/file/d/1v8vUadmU1_-o6Hx5lXWCJhrG9sHCl9q_/view?usp=sharing
        link_text: Termproject report
        quote: >
          系統晶片之嵌入式即時作業系統期末專題: Android APP 控制藍芽小車回傳實時影像
          <br />Embedded Real-Time Operating System for System-on-Chip Term Project : Real time Streaming on Arduino Car with App Controller  
        additional_links:
          - title:  TermProject-2021-EnbeddedSystem
            icon: fab fa-github
            url: https://github.com/FanChiMao/TermProject-2021-EnbeddedSystem     
          - title: demo video
            icon: fab fa-youtube
            url: https://youtu.be/YIfOnbJ-TMI  
        description: | # this will include new lines to allow paragraphs  
          ① 利用android app作為遙控器藍芽控制Arduino小車方向，並將小車鏡頭接收到的畫面實時回傳至手機。  
          ② 最終得分為93/100，為全班第四名。  

      - layout: left
        title: 2021 AICUP
        caption: Jan 2021 - Jun 2021
        link: https://aidea-web.tw/topic/9c88c428-0aa7-480b-85e0-2d8fb2fcf3fc
        link_text: Competition website
        quote: >
          水稻無人機全彩影像植株位置自動標註與應用
          <br />Competition on Automatic rice plant position labeling on true color images by UAS and its applications
        additional_links:
          - title: Competition-2021-Pytorch-YOLOv4
            icon: fab fa-github
            url: https://github.com/FanChiMao/Competition-2021-Pytorch-YOLOv4
          - title: award
            icon: fas fa-award
            url: https://i.imgur.com/hoBExox.jpg
        description: | # this will include new lines to allow paragraphs  
          ① 利用物件偵測模型(如:YOLOv4)來偵測空拍水稻圖的秧苗位置。  
          ② 擔任隊長職務，在523組參賽隊伍中，獲得全國第9名佳作。
          

# Footer
footer_show_references: 
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
