# Site
repository: sproogen/resume-theme
favicon: https://i.ibb.co/syrsmb1/026.png

# Content configuration version
version: 2

# Personal info
name: 范植貿
title: Chi-Mao Fan
email: qaz5517359@gmail.com
# website: www.github.com/sproogen/resume-theme

# Dark Mode (true/false/never)
darkmode: true

# Social links
# twitter_username: Fan_R_Mao
github_username:  FanChiMao
# stackoverflow_username: "17114617"
facebook_username: 52hzfan
instagram_username: 52hz_fan
linkedin_username: 植貿-范-432665220
# youtube_username: channel:fooUCIV7WMa5O_TZKZZSzXcLmmw


# Additional icon links
#additional_links:
# - title: itsgoingto.be
#  icon: fas fa-globe
#  url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
about_title: Personal Profile
about_profile_image: https://i.imgur.com/m2rDOMa.jpg
about_content: | # this will include new lines to allow paragraphs
  出生於1997年，生長於新竹，個性溫和善於傾聽，會站在別人的角度換位思考，不易與人發生爭執，因此在團隊合作中，可以良好的溝通及互動，因為影響團隊效率除了專業技能外，人與人之間和睦相處更是關鍵，我在露易莎打工時更深深體會了這點。  
  大學就讀元智大學電機系，畢業後發現相較於硬體領域，我對軟體方面更加有興趣，因此在考上中興大學電機系碩士班後，找了偏重於軟體開發的教授與實驗室，主要的研究領域為電腦視覺、影像處理與深度學習。  
  碩士期間主要研究影像修復(Image Restoration)任務中包括影像去噪(Image Denoising)、影像去模糊(Image Deblurring)、影像去雨(Imade Deraining)、影像去霧(Image Dehazing)與低光源增強(Low-light Enhancement)。  
  且由於對任何事物都充滿著好奇心並渴望能夠不斷地進步成長的個性。 碩士期間額外學習了物件偵測(Object Detection)、資料分析(Data Analyze)並參與全國性程式競賽，得到了不錯的成績。 除此之外，碩二時投稿4篇會議論文分別至ICLR (reject)、ISCAS (accept)、ICME (in review)與ICIP (in review)等國際會議，並參與校內語言中心課程學習英文口說與日文課程。  


content:
  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: 國立中興大學 (NCHU)
        caption: Sep 2020 - present
        sub_title: 電機工程研究所
        description: | # this will include new lines to allow paragraphs
          
      - layout: left
        title: 元智大學 (YZU)
        caption: Sep 2015 - Aug 2020
        sub_title: 電機工程學系
        description: | # this will include new lines to allow paragraphs
                            
  - title: Research Experiences # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: 碩士畢業論文
        caption: Sep 2021 - Mar 2022
        link: https://drive.google.com/file/d/1PKB0Mb02cmNcB5zCae_SYDbgPr4w86xy/view?usp=sharing
        link_text: Thesis pdf
        quote: >
          利用可選擇性殘差塊在改良式階層編解碼器網路實現影像修復
          <br />Image Restoration by Selective Residual Block on Improved Hierarchical Encoder-Decoder Networks  
        additional_links:
          - title:  Thesis
            icon: fab fa-github
            url: https://github.com/FanChiMao/SRMNet-thesis
          - title: HuggingFace
            icon: fas fa-play
            url: https://huggingface.co/spaces/52Hz/SRMNet_thesis
        description: | # this will include new lines to allow paragraphs
          ① 我們提出了改良版的階層式編解碼器架構: MINet+。  
          ② 我們提出了一種平衡型模塊，稱為選擇殘差模塊(Selective Residual Block)。  
          ③ 我們提出了一個全新的特徵融合方式，稱為選擇小波特徵融合(Selective Wavelet Feature Fusion)。  
          ④ 我們提出一個高性能的影像修復模型，能處理5種不同的影像修復任務，並測試於超過10個資料集。  
                  
      - layout: left
        title: IMBD 競賽
        caption: Sep 2021 - Dec 2021  
        link: https://imbd2021.thu.edu.tw/
        link_text: Competition website
        quote: >
          2021全國智慧製造大數據分析競賽
          <br />National Intelligent Manufacturing Big Data Analysis Competition  
        additional_links:
          - title:  Competition-2021-Pytorch-Reggression
            icon: fab fa-github
            url: https://github.com/FanChiMao/Competition-2021-Pytorch-Reggression
          - title: award
            icon: fas fa-award
            url: https://i.imgur.com/SIQyjTo.jpg
        description: | # this will include new lines to allow paragraphs  
          ① Python/Data Regression/MLP  
          ② 利用現成業界模具機台的參數數據，用深度學習方式預測晶圓或產品品質。  
          ③ 在118個隊伍中，得到前31名並通過初賽。  

      - layout: left
        title: 課堂期末專題
        caption: May 2021 - July 2021
        link: https://drive.google.com/file/d/1v8vUadmU1_-o6Hx5lXWCJhrG9sHCl9q_/view?usp=sharing
        link_text: Termproject report
        quote: >
          系統晶片之嵌入式即時作業系統期末專題: Android APP 控制藍芽小車回傳實時影像
          <br />Embedded Real-Time Operating System for System-on-Chip Term Project : Real time Streaming on Arduino Car with App Controller  
        additional_links:
          - title: TermProject-2021-EnbeddedSystem
            icon: fab fa-github
            url: https://github.com/FanChiMao/TermProject-2021-EnbeddedSystem     
          - title: demo video
            icon: fab fa-youtube
            url: https://youtu.be/YIfOnbJ-TMI  
        description: | # this will include new lines to allow paragraphs  
          ① Python/C/JavaScript/Raspberry Pi 3/Arduino/Android App/Communication protocol  
          ② 利用android app作為遙控器藍芽控制Arduino小車方向，並將小車鏡頭接收到的畫面實時回傳至手機。  
          ③ 最終得分為93/100，為全班第4名。  

      - layout: left
        title: AICUP 競賽
        caption: Jan 2021 - Jun 2021
        link: https://aidea-web.tw/topic/9c88c428-0aa7-480b-85e0-2d8fb2fcf3fc
        link_text: Competition website
        quote: >
          水稻無人機全彩影像植株位置自動標註與應用
          <br />Competition on Automatic rice plant position labeling on true color images by UAS and its applications
        additional_links:
          - title: Competition-2021-Pytorch-YOLOv4
            icon: fab fa-github
            url: https://github.com/FanChiMao/Competition-2021-Pytorch-YOLOv4
          - title: award
            icon: fas fa-award
            url: https://i.imgur.com/hoBExox.jpg
        description: | # this will include new lines to allow paragraphs  
          ① Python/Object Detection/Image Segmentation/YOLOv4/UNet  
          ② 利用物件偵測模型(如:YOLOv4)來偵測空拍水稻圖的秧苗位置。  
          ③ 擔任隊長職務，在523組參賽隊伍中，獲得全國第9名佳作。
          
      - layout: left
        title: 大學畢業專題
        caption: July 2016 - May 2017
        link: https://docs.google.com/document/d/1tA1TyLsBKkUloF144vLz7zFzpF9rVBwj/edit?usp=sharing&ouid=108348190349543369603&rtpof=true&sd=true
        link_text: Termproject report
        quote: >
          即時課堂互動Android App  
          <br />Classroom Interactive App 
        additional_links:
          - title: TermProject-2017-Java-AndroidStudio
            icon: fab fa-github
            url: https://github.com/FanChiMao/TermProject-2017-Java-AndroidStudio
          - title: ppt
            icon: fas fa-desktop
            url: https://docs.google.com/presentation/d/1YsvzB4KOTbtPYtGbjwFzsWaPwZb21d-g/edit?usp=sharing&ouid=108348190349543369603&rtpof=true&sd=true
        description: | # this will include new lines to allow paragraphs  
          ① JavaScript/SQL/Android App/Socket connection  
          ② 從零開始建構出一個完整功能的課堂互動應用程式，包含了網路傳輸、資料庫的創建。  
          ③ 最終得分為94/100，為全班排名前10%。  

  - title: Publications # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: SRMNet
        caption: Mar 2022
        quote: >
          Selective Residual M-Net for Real Image Denoising  
          <br /> 我們提出的SRMNet影像去雜訊模型，在SIDD資料集中，圖像評估指標排名世界第5名。 
        additional_links:
          - title: SRMNet
            icon: fab fa-github
            url: https://github.com/FanChiMao/SRMNet
          - title: arXiv
            icon: fas fa-book
            url: https://arxiv.org/abs/2203.01296
          - title: HuggingFace
            icon: fas fa-play
            url: https://huggingface.co/spaces/52Hz/SRMNet_real_world_denoising     
        
      - layout: left
        title: HWMNet
        caption: Feb 2022
        quote: >
          Half Wavelet Attention on M-Net+ for Low-Light Image Enhancement  
          <br /> 我們提出的HWNet影像低光源增強模型，在LOL資料集中，圖像評估指標排名世界第2名。  
        additional_links:
          - title: HWMNet
            icon: fab fa-github
            url: https://github.com/FanChiMao/HWMNet
          - title: arXiv
            icon: fas fa-book
            url: https://arxiv.org/abs/2203.01296
          - title: HuggingFace
            icon: fas fa-play
            url: https://huggingface.co/spaces/52Hz/HWMNet_lowlight_enhancement

      - layout: left
        title: SUNet
        caption: Dec 2021
        quote: >
          SUNet: Swin Transformer UNet for Image Denoising
          <br /> 利用Swin Tansformer為基礎架構，提出SUNet影像降噪模型，並被ISCAS 2022所接受。
        additional_links:
          - title: SUNet
            icon: fab fa-github
            url: https://github.com/FanChiMao/SUNet
          - title: arXiv
            icon: fas fa-book
            url: https://arxiv.org/abs/2202.14009
          - title: HuggingFace
            icon: fas fa-play
            url: https://huggingface.co/spaces/52Hz/SUNet_AWGN_denoising

      - layout: left
        title: CMFNet
        caption: Sep 2021
        quote: >
          Compound Multi-branch Feature Fusion for Real Image Restoration
          <br /> 提出的CMFNet模型，針對影像去模糊、影像去雨滴與影像去霧任務進行修復，並投稿至ICLR 2022。
        additional_links:
          - title: CMFNet
            icon: fab fa-github
            url: https://github.com/FanChiMao/CMFNet
          - title: arXiv
            icon: fas fa-book
            url: https://paperswithcode.com/paper/compound-multi-branch-feature-fusion-for-real
          - title: HuggingFace
            icon: fas fa-play
            url: https://huggingface.co/spaces/52Hz/CMFNet_deblurring

# Footer
footer_show_references: 
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
