# Site
repository: sproogen/resume-theme
favicon: https://i.ibb.co/syrsmb1/026.png

# Content configuration version
version: 2

# Personal info
name: 范植貿
title: Chi-Mao Fan
email: qaz5517359@gmail.com
# website: www.github.com/sproogen/resume-theme

# Dark Mode (true/false/never)
darkmode: true

# Social links
# twitter_username: Fan_R_Mao
github_username:  FanChiMao
# stackoverflow_username: "17114617"
facebook_username: 52hzfan
instagram_username: 52hz_fan
linkedin_username: 植貿-范-432665220
# youtube_username: channel:fooUCIV7WMa5O_TZKZZSzXcLmmw


# Additional icon links
#additional_links:
# - title: itsgoingto.be
#  icon: fas fa-globe
#  url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
about_title: Personal Profile
about_profile_image: https://i.imgur.com/m2rDOMa.jpg
about_content: | # this will include new lines to allow paragraphs
  **Hello World! 我是范植貿，今年25歲，來自新竹，現居台中。**
  
  2022畢業於中興大學研究所，


content:
  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: 國立中興大學 (NCHU)
        caption: 2020.9 - present
        sub_title: 電機工程研究所
        description: | # this will include new lines to allow paragraphs
          
      - layout: left
        title: 元智大學 (YZU)
        caption: 2015.9 - 2020.8
        sub_title: 電機工程學系
        description: | # this will include new lines to allow paragraphs
                   
  - title: Research Experiences # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: The Boring Company
        link: boringcompany.com
        # link_text: boringcompany.com
        sub_title: Senior Network System Administrator
        caption: November 2017 - Present
        quote: >
          Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
        description: | # this will include new lines to allow paragraphs
            Every company needs its networks properly administered and The Boring Compay is no exception. Digging holes is hard and I play my part making sure the whole company stays connected. I lead a team of 5 people and enjoy driving the company to try new technologies.

          
  - title: Research Experiences # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: 碩士論文
        caption: Sep 2021 - Mar 2022
        quote: >
          利用可選擇性殘差塊在改良式階層編解碼器網路實現影像修復
          <br />Image Restoration by Selective Residual Block on Improved Hierarchical Encoder-Decoder Networks  
        link: https://github.com/FanChiMao/SRMNet-thesis
        link_text: Thesis
        additional_links:
          - title:  Thesis
            icon: fab fa-github
            url: https://github.com/FanChiMao/SRMNet-thesis
        description: | # this will include new lines to allow paragraphs
          <br />① We proposed an improved hierarchical encoder-decoder network called M-Net+.
          <br />② We proposed an efficient residual block named Selective Residual Block (SRB), which is a balance between the complexity and efficacy by several ablation studies..
          <br />③ We proposed a novel feature fusion method named SWFF which is considered with the feature information of wavelet transformation.
          <br />④ We proposed a restoration model which can handle 5 different restoration tasks including denoising, deblurring, dehazing, deraining and image enhancement. And test on over 10 datasets which gets the competitive results and visual performances.

      - layout: left
        title: 畢業專題 (2017)
        caption: 2016.7 - 2017.5
        link: https://github.com/FanChiMao/TermProject-2015-Java-AndroidStudio
        link_text: Classroom Interaction App
        additional_links:
          - title:  Android App
            icon: fab fa-github
            url: github.com/FanChiMao/TermProject-2015-Java-AndroidStudio
        description: | # this will include new lines to allow paragraphs
          
          
      - layout: left
        title: AICUP競賽 (2020)
        caption: 2020.2 - 2020.6
        link: https://github.com/FanChiMao/Competition-2021-Pytorch-YOLOv4
        link_text: YOLOv4 object detection
        additional_links:
          - title:  YOLOv4
            icon: fab fa-github
            url: github.com/FanChiMao/Competition-2021-Pytorch-YOLOv4
        description: | # this will include new lines to allow paragraphs
          在研究所一下時，教授要求我們組隊參加由教育部與工研院共同舉辦的AICUP比賽，並指派我當隊長。 在修碩班課程之餘，挪出一部分時間參加比賽，說實話有些許吃力，這也是我第一次參加程式類別的比賽，也是第一次擔任隊長的職位。 一開始對自己的程式能力並沒有很有自信，覺得電機出身的我，很難與資工拚搏，但最終在523隊參賽隊伍中脫穎而出，得到了全國大專院校組第9名的佳績，也讓我對自己各方面的能力更有自信!
          
  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in networks and software engineering some of my other interests and hobbies are:
      - Rock climbing
      - Gaming
      - Knitting
      - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)

      Look at this cool image  
      ![Trees](/modern-resume-theme/images/landscape-trees.jpg "Trees")

# Footer
footer_show_references: 
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
